import { ref } from 'vue';

export function createDashboardElementEditorState() {
  return {
    elementName: ref(''),
    elementType: ref('chart'),
    elementChartType: ref('line'),
    xField: ref(''),
    measureFields: ref(''),
    valueField: ref(''),
    resultLimit: ref(25),
    resultLimitExplicit: ref(false),
    showLegend: ref(true),
    showTooltip: ref(true),
    columnsText: ref(''),
    tableDisplayMode: ref(''),
    tablePageSize: ref(25),
    tableGroupFieldsText: ref(''),
    tableFiltersText: ref(''),
    tableActionsText: ref(''),
    tableEnableSearch: ref(false),
    tableEnableFilters: ref(false),
    tableEnableSorting: ref(true),
    tableEnableRowSelection: ref(false),
    tableEnableExport: ref(false),
    tableEnablePagination: ref(false),
    tableHeightMode: ref<'auto-content' | 'fixed'>('fixed'),
    tableShowTotal: ref(false),
    tableTotalColumnsText: ref(''),
    tableTotalLabel: ref('Total'),
    tableTotalLabelColumn: ref(''),
    tableDataMode: ref<'raw' | 'series'>('raw'),
    tableFillMissingTimeBuckets: ref(false),
    tableTimeBucketInterval: ref<'auto' | 'day' | 'hour' | 'month' | 'week'>('auto'),
    tableTimeBucketFillValue: ref<number | null>(null),
    tableHeaderBg: ref('#f8fafc'),
    tableHeaderText: ref('#111827'),
    tableRowBg: ref('#ffffff'),
    tableRowText: ref('#111827'),
    tableShowBorders: ref(false),
    tableAlternateRowBg: ref('#f9fafb'),
    tableBorderColor: ref('#e5e7eb'),
    tableBorderRadius: ref('0'),
    tableCellPadding: ref('medium'),
    tableFormat: ref(''),
    tableHideTitle: ref(false),
    tableShadow: ref('none'),
    tableGroupShowTotals: ref(false),
    tableGroupCollapsed: ref(false),
    tableConditionalFormattingText: ref(''),
    calculatedFieldsText: ref(''),
    cardYField: ref(''),
    cardTrendField: ref(''),
    cardComparisonField: ref(''),
    cardComparisonContext: ref(''),
    cardSupportingField: ref(''),
    cardSupportingAggregation: ref('avg'),
    cardSupportingFormat: ref('number'),
    cardSupportingPrecision: ref<number | null>(null),
    cardSupportingLabel: ref(''),
    cardSupportingTone: ref('default'),
    cardComparisonDisplayMode: ref<'amount' | 'both' | 'percentage' | 'value'>('both'),
    cardComparisonDirection: ref<'higher-is-better' | 'lower-is-better' | 'none'>('higher-is-better'),
    cardLayout: ref('single'),
    cardType: ref('standard'),
    cardLayoutDesign: ref('standard'),
    cardLayoutPreset: ref('default'),
    cardWrapperTitle: ref(''),
    cardShowWrapperTitle: ref(false),
    cardTitle: ref(''),
    cardBackgroundColor: ref(''),
    cardTitleBackground: ref(''),
    cardTitleColor: ref(''),
    cardValueBackground: ref(''),
    cardValueColor: ref(''),
    cardBorderRadius: ref(''),
    cardColorScheme: ref(''),
    cardCustomClassName: ref(''),
    cardInnerGap: ref(''),
    cardOuterGap: ref(''),
    cardShadow: ref(''),
    cardShowTrend: ref(false),
    cardShowIndicator: ref(false),
    cardShowSparkline: ref(false),
    cardStatusIndicatorMode: ref<'threshold' | 'trend'>('trend'),
    cardStatusIndicatorPolarity: ref<'higher-is-better' | 'lower-is-better'>('higher-is-better'),
    cardStatusIndicatorGoodThreshold: ref<number | null>(null),
    cardStatusIndicatorWarningThreshold: ref<number | null>(null),
    cardTopRowContent: ref('title'),
    cardBottomRowContent: ref('value'),
    cardRowHeightRatio: ref('1:1'),
    cardGridColumns: ref(2),
    cardTitlePosition: ref('top'),
    cardTitleFontSize: ref('sm'),
    cardValueFontSize: ref('3xl'),
    cardSparklineField: ref(''),
    cardSparklineColor: ref(''),
    cardSparklineType: ref('area'),
    cardShowMinMaxAvg: ref(false),
    cardFormatType: ref('number'),
    cardUnit: ref('auto'),
    cardPrecision: ref<number | null>(null),
    cardPrefix: ref(''),
    cardSuffix: ref(''),
    cardCurrencySymbol: ref(''),
    cardAggregationType: ref('sum'),
    matrixRowFieldsText: ref(''),
    matrixColumnFieldsText: ref(''),
    matrixValueFieldsText: ref(''),
    matrixDisplayMode: ref(''),
    matrixShowValueHeaders: ref(false),
    matrixRowHeaderLabel: ref(''),
    matrixColumnHeaderLabel: ref(''),
    matrixValueHeaderLabel: ref(''),
    matrixRowHeaderWidth: ref(''),
    matrixValueHeaderWidth: ref(''),
    matrixRowHeaderWidthType: ref<'auto' | 'fixed' | 'full'>('auto'),
    matrixColumnHeaderWidthType: ref<'auto' | 'fixed' | 'full'>('auto'),
    matrixColumnHeaderWidth: ref(''),
    matrixColumnWidthsText: ref(''),
    matrixRowDataDisplayMode: ref('repeat'),
    matrixFiltersText: ref(''),
    matrixColumnDataDisplayMode: ref('repeat'),
    matrixShowTitle: ref(true),
    matrixTitleFontSize: ref('text-base'),
    matrixTitleFontWeight: ref('font-semibold'),
    matrixTitleColor: ref('#111827'),
    matrixHeaderAlign: ref('text-left'),
    matrixHeaderFontWeight: ref('font-semibold'),
    matrixRowHeaderAlign: ref('text-left'),
    matrixRowHeaderFontWeight: ref('font-medium'),
    matrixRowAlign: ref('text-left'),
    matrixRowFontWeight: ref('font-normal'),
    matrixConditionalFormattingText: ref(''),
    matrixMultiSortText: ref(''),
    matrixDefaultRowCollapseState: ref(''),
    matrixDefaultColumnCollapseState: ref(''),
    matrixSortBy: ref(''),
    matrixSortDirection: ref('asc'),
    matrixRowCollapseFieldsText: ref(''),
    matrixColumnCollapseFieldsText: ref(''),
    matrixShowRowTotals: ref(false),
    matrixShowColumnTotals: ref(false),
    matrixShowRowSubtotals: ref(false),
    matrixShowColumnSubtotals: ref(false),
    matrixEnableRowCollapse: ref(false),
    matrixEnableColumnCollapse: ref(false),
    matrixShowBorders: ref(false),
    matrixBorderColor: ref('#d1d5db'),
    matrixHeaderBg: ref('#f8fafc'),
    matrixHeaderText: ref('#111827'),
    matrixRowHeaderBg: ref('#ffffff'),
    matrixRowHeaderText: ref('#111827'),
    matrixRowBg: ref('#ffffff'),
    matrixRowText: ref('#111827'),
    matrixFontFamily: ref(''),
    matrixFontSize: ref(''),
    chartShowGrid: ref(true),
    chartShowXAxis: ref(true),
    chartShowYAxis: ref(true),
    chartShowDataLabels: ref(false),
    chartColorTheme: ref(''),
    chartCustomColorsText: ref(''),
    chartDataLabelPosition: ref(''),
    chartXAxisFormat: ref(''),
    chartXAxisGrouping: ref(''),
    chartXAxisSortOrder: ref('asc'),
    chartXAxisDateFormat: ref(''),
    chartXAxisDateFormatParameter: ref(''),
    chartXAxisDateFormatsText: ref(''),
    chartXAxisDateMidnightFormat: ref(''),
    chartXAxisDateMidnightFormatsText: ref(''),
    chartBooleanFalseLabel: ref(''),
    chartBooleanTrueLabel: ref(''),
    chartRangeSize: ref<number | null>(null),
    chartRangeStart: ref<number | null>(null),
    chartWeekNumbering: ref(''),
    chartWeekStartDay: ref(''),
    chartXAxisDisplayField: ref(''),
    chartXAxisFiscalStart: ref<number | null>(null),
    chartXAxisLabelAlignment: ref(''),
    chartXAxisLabelDisplay: ref(''),
    chartXAxisLabelRotation: ref<number | null>(null),
    chartXAxisSortField: ref(''),
    chartXAxisValueField: ref(''),
    chartXAxisYearType: ref(''),
    chartLegendPosition: ref('top'),
    chartLegendMarkerStyle: ref(''),
    chartStackBars: ref(false),
    chartTopN: ref<number | null>(null),
    chartLegendItemsPerPage: ref<number | null>(null),
    chartShowExportMenu: ref(false),
    chartExportPrint: ref(true),
    chartExportPng: ref(true),
    chartExportJpeg: ref(true),
    chartExportPdf: ref(true),
    chartExportSvg: ref(true),
    chartSpacingPreset: ref(''),
    chartPaddingTop: ref<number | null>(null),
    chartPaddingRight: ref<number | null>(null),
    chartPaddingBottom: ref<number | null>(null),
    chartPaddingLeft: ref<number | null>(null),
    chartTheme: ref(''),
    chartValueDisplay: ref(''),
    chartXValueColorsText: ref(''),
    chartSortBy: ref(''),
    chartSortDirection: ref('asc'),
    chartEnableY2: ref(false),
    chartXAxisLabel: ref(''),
    chartYAxisLabel: ref(''),
    chartY2AxisLabel: ref(''),
    chartYAxisStartMode: ref<'auto' | 'zero'>('zero'),
    chartYAxisPaddingMode: ref<'auto' | 'none' | 'zero-centered'>('none'),
    chartYAxisPaddingRatio: ref<number | null>(null),
    chartYAxisTickPadding: ref<number | null>(null),
    chartYAxisTitlePadding: ref<number | null>(null),
    chartMixedAxisPrimaryHeadroomRatio: ref<number | null>(null),
    chartY2AxisStartMode: ref<'auto' | 'zero'>('zero'),
    chartY2AxisPaddingMode: ref<'auto' | 'none' | 'zero-centered'>('none'),
    chartY2AxisPaddingRatio: ref<number | null>(null),
    chartLineInterpolation: ref<'curved' | 'straight'>('curved'),
    chartLineTension: ref<number | null>(null),
    chartFillMissingTimeBuckets: ref(false),
    chartTimeBucketInterval: ref<'auto' | 'day' | 'hour' | 'month' | 'week'>('auto'),
    chartTimeBucketFillValue: ref<number | null>(null),
    chartTimeZone: ref(''),
    chartSeriesLabelsText: ref(''),
    chartSeriesColorsText: ref(''),
    chartSeriesTypesText: ref(''),
    chartSeriesChartTypesText: ref(''),
    chartSeriesAxesText: ref(''),
    chartSeriesFormatText: ref(''),
    chartSeriesDecimalsText: ref(''),
    chartSeriesCurrencySymbolText: ref(''),
    chartSeriesPrefixText: ref(''),
    chartSeriesThousandsSeparatorText: ref(''),
    filterField: ref(''),
    filterInputType: ref('single-select'),
    filterOperator: ref('equals'),
    filterTarget: ref('all'),
    filterValue: ref(''),
    filterDatePickerDisplayMode: ref<'split-date-time' | 'native'>('native'),
    filterDateRangeDisplayMode: ref<'button' | 'datetime-fields' | 'inline' | 'range-picker'>('button'),
    filterPeriodActiveColor: ref(''),
    filterPeriodBackgroundColor: ref(''),
    filterPeriodDatePickerTheme: ref<'default' | 'legacy' | 'minimal'>('default'),
    filterPeriodNavigationStyle: ref<'text' | 'icons'>('text'),
    filterShowPeriodBottomDivider: ref(true),
    filterChrome: ref('card'),
    filterContainerId: ref(''),
    containerBackgroundColor: ref(''),
    containerBorderColor: ref(''),
    containerBorderRadius: ref('8'),
    containerBorderWidth: ref('1'),
    containerColumns: ref(4),
    containerGap: ref('12'),
    containerPadding: ref('14'),
    containerShowTitle: ref(false),
    configError: ref('')
  };
}

export type DashboardElementEditorState = ReturnType<typeof createDashboardElementEditorState>;
